name: Desplegar sitio web en Github Pages 

on:
  push:
    branches:
      - main 

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer ckeckout del repositorio
        uses: actions/ckeckout@v3

      - name: Configurar node
        uses: action/setup-node@v3
        with:
          node-version: 18
      - run: npm install 
      - run: npm test 


      -name: Desplegar en github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_tokens: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: true